### ISSUE TITLE
Feature Request:  $params['post_publication_start'] for Nos\BlogNews\Model_Post::get_query

### ISSUE THREAD

**Issue by ounziw** [novius-os/noviusos_blognews#11]
I'm planning to create a monthly archive for blog posts.

I need a new parameter for Nos\BlogNews\Model_Post::get_query.

```
if (!empty($params['post_publication_start'])) {
    // pick up the posts after $params['post_publication_start']['start']
    $query->where(array('post_publication_start', '>=', $params['post_publication_start']['start']));

    // pick up the posts before $params['post_publication_start']['end']
    $query->where(array('post_publication_start', '<', $params['post_publication_start']['end']));
}
```

For example, If I want to pickup the blog posts of May 2013, 
I will set $params['post_publication_start'] as below.

```
$params['post_publication_start'] = array(
    'start'=> '2013-05-01 00:00:00',
    'end'=> '2013-06-01 00:00:00'
);
```

**Comment by felixgilles** [comment]
Hi Fumito,

You can define in front config (noviusos_blognews::controller/front) a key 'query_callback'. Assign to it a callback function which take $query, $params, $controller for parameters.

https://github.com/novius-os/noviusos_blognews/blob/master/chiba/classes/controller/front.ctrl.php#L495

With that, you can add your specific params for monthly archive.

For example:

``` php
Event::register_function('config|noviusos_blognews::controller/front', function(&$config)
{
    $config['query_callback'] = function($query, $params, $controller) {
        if (!empty($params['post_publication_start'])) {
            // pick up the posts after $params['post_publication_start']['start']
            $query->where(array('post_publication_start', '>=', $params['post_publication_start']['start']));

            // pick up the posts before $params['post_publication_start']['end']
            $query->where(array('post_publication_start', '<', $params['post_publication_start']['end']));
        }
    }
}
```

**Comment by sdrdis** [comment]
Hi Fumito,

The solution provided by @felixgilles works pretty fine if you want to change the query on front.

About the `get_query` called by `get_all` / `count_all` methods, your request is legitimate; I think one problem is that `get_query` does not allow query customization. The problem is not on the `get_query` method directly but on the `get_all` / `count_all` methods: for example, if you want to get a list of model instances with additionnal conditions / related, you will have to rewrite the `get_all` method content.

I thought a little bit about this and here is the solution I just came up with: I added a new key `query_options` which is the same sent to the fuel orm `find` function. This way you can have full control over the query:

Here are my changes: https://github.com/novius-os/noviusos_blognews/commit/b7b7a70f5109750c6877da8a8c2bbebf128be3b5

This way, params you have to send are still quite simple, but using the fuel orm syntax:

```
$params['query_options'] = array(
    'where' => array(
        array('post_publication_start', '>', '2013-05-01 00:00:00'),
        array('post_publication_start', '<', '2013-06-01 00:00:00'),
    ),
);
```

Does it seems right to both of you ?

**Comment by ounziw** [comment]
Thanks, @felixgilles and @sdrdis.

I will use 'query_callback'.
That's OK for query.

I'm considering to create a URL routing. 
Maybe, URL/archives/201305.html or URL/archives/2013/05.html 

Which will you recommend?
Does it conflict to Novius OS's routing?

**Comment by felixgilles** [comment]
My opinion:

Create a new app which extends blog (if you want to use blog).
http://docs-api.novius-os.org/en/chiba.1/php/configuration/application/metadata.html#extends

In this app, 
- create a front controller which extends the native blog front controller.
- in the metadata file, declare a new enhancer which has a urlEnhancer setted to your new front controller

In the new front controller, extend the action_main method to manage archives like categories or tags.

And between 201305.html and 2013/05.html, I prefer 2013/05.html

**Comment by ounziw** [comment]
Thanks, @felixgilles,

I will extend blog appilication.

**Comment by felixgilles** [comment]
You're welcome!
Keep me informed.
